name: Android upload

on:
  push:
    branches:    
      - 'prod'
    paths:
      - "src/android/**"
      - ".github/workflows/upload-android.yml"

env:
  PACKAGE_NAME: com.salvai.centrum
  WORKING_DIRECTORY: src
  SERVICE_ACCOUNT_JSON: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
  KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
  KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
  RELEASE_KEY_STORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

jobs:
  deploy:
    runs-on: ubuntu-20.04        
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create service-account.json
        run: echo -n "$SERVICE_ACCOUNT_JSON" > service-account.json

      - name: Insert keystore properties
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          sed -i -e "s%STORE_PASSWORD%${{env.STORE_PASSWORD}}%g" android/build.gradle
          sed -i -e "s%KEY_PASSWORD%${{env.KEYSTORE_PASSWORD}}%g" android/build.gradle
          sed -i -e "s%KEYSTORE_ALIAS%${{env.KEYSTORE_ALIAS}}%g" android/build.gradle

      - name: Create release keystore
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: echo -n "$RELEASE_KEY_STORE_BASE64" | base64 --decode > android/keystore.keystore

      - name: Export signed apk and release to internal testing
        uses: dulvui/libgdx-android-upload@v1.3
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          working-directory: ${{ env.WORKING_DIRECTORY }}
          changes-not-sent-for-review: 'true'
